### ISSUE TITLE
Clean data

### ISSUE THREAD

**Issue by dewarian** [dewarian/frontend-data#1]
## Data cleansing

Record the process of how to clean data in a functional pattern.
Data could be survey data or RDW data.

### Tasks

- [ ] Retrieve the data.
- [ ] Filter data on the specifications
  a. survey data: Clean it to be digestible. e.g. eye-colour only hex
  b. RDW data: Array of objects only return needed variables.
    - [ ] _Research specific data you want to use for the charts (must fit in theme)_

### Requirements

The data cleansing process must be done with the following specifications:
1. Written in a functional pattern
2. Should be reusable.
3. Must at least use the following methods;
  * [`.map()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map)
  * [`.filter()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter)
 * Should also use a `forEach` when iterating through the array instead of manipulating the array.
