### ISSUE TITLE
Create a barchart

### ISSUE THREAD

**Issue by dewarian** [dewarian/frontend-data#4]
Use D3 to create a bar chart, first with prop data, when successfully integrate my own dataset.

#### Tasks
- [ ] Create SVG
- [ ] Define the scales for X and Y axis.
- [ ] Add labels to X and Y axis.
- [ ] Add title to graph.

#### Result

The result after this issue would be a single bar chart that shows that the Netherlands is only beginning with greener transport.

**Comment by dewarian** [comment]
To +1 this, I could search for another dataset that checks public transport and improves it with greener transport
